# Site settings
title: RoyCheng Blog
SEOTitle: RoyCheng | RoyCheng Blog
header-img: img/gif/background_cut.gif
email: roycheng1997@gmail.com
description: "Quant World"
keyword: "Roy, RoyCheng Blog, XiaoCheng, 程骁, iOS, Apple, iPhone"
url: "http://coachmanfund.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/CoachmanFund/coachmanfund.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "M.S. candidate of Mathematics in Finance at NYU Courant, Quantitative Analyst"
sidebar-avatar: /img/BS_Shot.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
# weibo_username:     
#zhihu_username:     
github_username:    coachmanfund
linkedin_username:  cheng-xiao
facebook_username:  roycheng1997

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# gem plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Gems
# from PR#40, to support local preview for Jekyll 3.0
#gems: [jekyll-paginate,jekyll-feed]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
mathjax: true
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 4312ab68d07289784782                            #生成的clientID
  clientSecret: 7cea7ddbc7f580e4c46d122a42c3a296f7f15ef2    #生成的clientSecret
  repo: roycheng1997.github.io    #仓库名称
  owner: RoyCheng1997    #github用户名
  admin: RoyCheng1997
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 94dc2768a639c61a08c301e586f961b0

# Google Analytics
ga_track_id: 'UA-154478859-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Xingqi Li (CMU MSCF Candidate)",
        href: "https://github.com/Starishli"
    },
      {
        title: "Leyang Zhang (CMU MSCF Candidate)",
        href: "https://github.com/LeyangZhang"
    }
]

markdown: kramdown